const ActionTypes = {
  ADD_MARKER: 'ADD_MARKER',
  UPDATE_MARKER_DRAFT: 'UPDATE_MARKER_DRAFT',
  REMOVE_MARKER: 'REMOVE_MARKER',
  TOGGLE_MARKER: 'TOGGLE_MARKER',
  EDIT_MARKER: 'EDIT_MARKER',
  START_EDIT_MARKER: 'START_EDIT_MARKER',
  STOP_EDIT_MARKER: 'STOP_EDIT_MARKER'
};

export default ActionTypes;
